# YOLOv5 标准化配置文件
# 版本: 2.0
# 最后更新: 2024-05-23

# 硬件配置
hardware:
  device: cuda:0  # 默认使用GPU 0
  workers: 8      # 数据加载线程数

# 路径配置
paths:
  project_root: E:/github/Integration-procedure/src/features/yolo_detect
  dataset: 
    root: ${paths.project_root}/datasets/yolo
    train: ${paths.dataset.root}/train
    val: ${paths.dataset.root}/val
  weights_dir: ${paths.project_root}/models/weights

# 模型参数
model:
  name: yolov5s
  pretrained: false
  input_size: [640, 640]  # 输入尺寸 [width, height]
  num_classes: 80

# 训练参数
training:
  epochs: 1
  batch_size: 1
  optimizer: 
    type: Adam
    lr: 0.001
    weight_decay: 0.0005
  scheduler:
    type: CosineAnnealing
    t_max: 50

# 数据增强配置（Albumentations兼容格式）
augmentation:
  geometric:
    random_resized_crop:
      min_scale: 0.5
      max_scale: 1.0
      aspect_ratio: [0.75, 1.33]
      interpolation: 1  # 与代码中的cv2.INTER_LINEAR对应
    rotation:
      degrees: 15
      p: 0.5
    scale: 
      min: 0.5
      max: 0.8
      p: 0.8
    translation:
      x: 0.2
      y: 0.2
      p: 0.5

  color:
    hsv: 
      h: 0.015
      s: 0.7
      v: 0.4
    contrast: 0.2
    brightness: 0.2

  special:
    mosaic: 
      enabled: True
      p: 1.0
    mixup: 
      enabled: False
      alpha: 0.2

# 验证参数
validation:
  batch_size: 16
  interval: 1    # 每N个epoch验证一次
  conf_thres: 0.4
  iou_thres: 0.5

# 类别标签 (COCO 80类)
class_labels:
  names: &id001 [
    'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep',
    'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella',
    'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
    'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
    'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork',
    'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange',
    'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair',
    'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
    'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
    'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
    'scissors', 'teddy bear', 'hair drier', 'toothbrush'
  ]
  visualization:
    colors: random  # 可选 [random, coco, custom]
    line_thickness: 2

# 日志配置
logging:
  tensorboard: True
  wandb: False
  checkpoint:
    interval: 10    # 每N个epoch保存一次权重
    save_best: True